# Generated by Django 4.2.3 on 2023-07-28 18:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_string', models.CharField(max_length=140)),
                ('creation_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_votes', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RankedTextReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.CharField(max_length=200)),
                ('report_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('ranked_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TextRanker.rankedtext')),
            ],
        ),
    ]
