# Generated by Django 4.2.3 on 2023-07-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankedtext',
            name='text_string',
            field=models.TextField(max_length=140),
        ),
    ]
