# Generated by Django 4.2.3 on 2023-07-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0003_alter_rankedtextreport_report_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankedtext',
            name='text_string',
            field=models.TextField(max_length=140, unique=True),
        ),
    ]
