# Generated by Django 4.2.3 on 2023-07-31 23:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0004_alter_rankedtext_text_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boop_text', models.TextField(max_length=140, unique=True)),
                ('creation_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_foops', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BoopReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.TextField(max_length=500)),
                ('report_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('boop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TextRanker.boop')),
            ],
        ),
        migrations.RemoveField(
            model_name='rankedtextreport',
            name='ranked_text',
        ),
        migrations.DeleteModel(
            name='RankedText',
        ),
        migrations.DeleteModel(
            name='RankedTextReport',
        ),
    ]
