# Generated by Django 4.2.3 on 2023-08-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0005_boop_boopreport_remove_rankedtextreport_ranked_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoopSubmissionWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField()),
                ('last_submitted', models.DateTimeField()),
                ('submit_attempt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FoopUserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField()),
                ('last_submitted', models.DateTimeField()),
            ],
        ),
    ]
