# Generated by Django 4.2.3 on 2023-08-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0006_foopsubmissionwarning_foopusersubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foopusersubmission',
            name='user_ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
