# Generated by Django 4.2.3 on 2023-08-02 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextRanker', '0007_alter_foopusersubmission_user_ip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoopUserSubmission',
            new_name='UserPOSTSubmission',
        ),
        migrations.RenameModel(
            old_name='FoopSubmissionWarning',
            new_name='UserPOSTSubmissionWarning',
        ),
    ]
